### ISSUE TITLE
MJFutureBatch with serial execution

### ISSUE THREAD

**Issue by RubenVot** [mobilejazz/MJCocoaCore#1]
Would be nice if MJFutureBatch could be executed in serial

**Comment by vilanovi** [comment]
Ok, feature implemented on MJCocoaCore pod version 2.2.2

**Comment by RubenVot** [comment]
That's customer support!!

**Comment by vilanovi** [comment]
Important: Note that what is serial is the delivery of the results, not the "execution", as futures are filled independently from the batch.
